name: Build ImmortalWRT

on:
  workflow_dispatch:
    inputs:
      config_file:
        description: 'Config file to use for the build'
        required: true
        default: 'immortalwrt.config'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Init Env
        run: |
          [ $(sudo docker images -q | wc -l) -eq 0 ] || sudo docker rmi $(docker images -q)
          sudo rm -rf /usr/local/lib/android/ /etc/apache2/ /etc/default/mono-xsp4 /etc/nginx/ /opt/hostedtoolcache/ /usr/local/share/chrom* /usr/local/share/edge_driver /usr/local/share/gecko_driver /usr/share/java/selenium-server.jar /usr/local/share/powershell/ /usr/local/share/vcpkg /usr/share/miniconda /home/linuxbrew
          sudo rm -rf $JAVA_HOME_8_X64 $JAVA_HOME_17_X64 $GRAALVM_11_ROOT
          sudo rm -rf /usr/share/dotnet/ /usr/share/php* /opt/az
          df -h $GITHUB_WORKSPACE

      - name: Checkout
        uses: actions/checkout@v5

      - name: Checkout ImmortalWRT
        uses: actions/checkout@v5
        with:
          repository: immortalwrt/immortalwrt
          ref: openwrt-24.10
          fetch-depth: 1
          path: immortalwrt

      - name: Cache tools and toolchain
        uses: actions/cache@v4
        with:
          path: |
            immortalwrt/build_dir
          key: ${{ runner.os }}-immortalwrt-build-tools-$(git rev-parse --short HEAD)
          restore-keys: |
            ${{ runner.os }}-immortalwrt-build-tools-

      - name: Set LAN IP
        run: |
          sed -i 's/192.168.1.1/192.168.10.1/g' immortalwrt/package/base-files/files/bin/config_generate

      - name: Set Config
        run: |
          [ -e config/${{ github.event.inputs.config_file }} ] && cp config/${{ github.event.inputs.config_file }} immortalwrt/.config || exit 1

      - name: Build ImmortalWRT
        run: |
          cd immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          make defconfig
          make download -j$(nproc)
          make -j$(nproc)

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-build
          path: |
            immortalwrt/bin/targets/*/*/*
            !immortalwrt/bin/targets/*/*/packages/*
